import { NextRequest, NextResponse } from "next/server";
import * as XLSX from "xlsx";
import { connectDB } from "@/lib/db";
import { getCurrentUser, requestContext } from "@/lib/auth";
import type { Model } from "mongoose";

import { Product } from "@/models/Product";
import { Customer } from "@/models/Customer";
import { Sale } from "@/models/Sale";
import { Invoice } from "@/models/Invoice";
import { Quotation } from "@/models/Quotation";
import { Expense } from "@/models/Expense";
import { Shipment } from "@/models/Shipment";
import { InventoryMovement } from "@/models/InventoryMovement";
import { Employee } from "@/models/Employee";
import { logActivity } from "@/models/ActivityLog";

export const dynamic = "force-dynamic";

// Full database backup as one .xlsx workbook — a sheet per module, filtered to
// a date range. Owner-only (it includes every module, including employees).
type Source = {
  sheet: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  model: Model<any>;
  filter?: Record<string, unknown>;
  omit?: string[];
};

const SOURCES: Source[] = [
  { sheet: "Products", model: Product },
  { sheet: "Customers", model: Customer },
  { sheet: "Sales", model: Sale },
  { sheet: "Invoices", model: Invoice },
  { sheet: "Quotations", model: Quotation },
  { sheet: "Accounting", model: Expense },
  { sheet: "Air Freight", model: Shipment, filter: { freightType: "air" } },
  { sheet: "Sea Freight", model: Shipment, filter: { freightType: "sea" } },
  { sheet: "Inventory Moves", model: InventoryMovement },
  // Never export password hashes.
  { sheet: "Employees", model: Employee, omit: ["passwordHash"] },
];

// Turn one Mongo value into a single spreadsheet cell.
function cell(value: unknown): string | number | boolean {
  if (value === null || value === undefined) return "";
  if (value instanceof Date) return value.toISOString();
  if (typeof value === "object") {
    const v = value as { toHexString?: () => string };
    if (typeof v.toHexString === "function") return v.toHexString(); // ObjectId
    try {
      return JSON.stringify(value);
    } catch {
      return String(value);
    }
  }
  if (typeof value === "number" || typeof value === "boolean") return value;
  return String(value);
}

function toRow(doc: Record<string, unknown>, omit: string[] = []) {
  const drop = new Set(["__v", "passwordHash", ...omit]);
  const row: Record<string, string | number | boolean> = {};
  for (const [key, val] of Object.entries(doc)) {
    if (drop.has(key)) continue;
    row[key] = cell(val);
  }
  return row;
}

export async function GET(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user || user.role !== "founder-ceo") {
    return NextResponse.json({ error: "Access denied" }, { status: 403 });
  }

  try {
    await connectDB();
    const { searchParams } = req.nextUrl;
    const fromStr = searchParams.get("from") || "";
    const toStr = searchParams.get("to") || "";

    const from = fromStr ? new Date(`${fromStr}T00:00:00.000Z`) : new Date(0);
    // Inclusive of the whole "to" day.
    const to = toStr
      ? new Date(new Date(`${toStr}T00:00:00.000Z`).getTime() + 24 * 60 * 60 * 1000 - 1)
      : new Date();
    if (isNaN(from.getTime()) || isNaN(to.getTime()) || from > to) {
      return NextResponse.json({ error: "Invalid date range." }, { status: 400 });
    }

    const dateFilter = { createdAt: { $gte: from, $lte: to } };
    const wb = XLSX.utils.book_new();
    const counts: Record<string, number> = {};

    for (const src of SOURCES) {
      const docs = (await src.model
        .find({ ...(src.filter ?? {}), ...dateFilter })
        .sort({ createdAt: 1 })
        .lean()) as Record<string, unknown>[];
      counts[src.sheet] = docs.length;
      const rows = docs.length
        ? docs.map((d) => toRow(d, src.omit))
        : [{ Note: "No records in this date range" }];
      const ws = XLSX.utils.json_to_sheet(rows);
      // Sheet names are capped at 31 chars and can't contain : \ / ? * [ ]
      XLSX.utils.book_append_sheet(wb, ws, src.sheet.slice(0, 31));
    }

    // A small summary sheet up front.
    const summary = [
      { Field: "Business", Value: "SOMART" },
      { Field: "From", Value: fromStr || "beginning" },
      { Field: "To", Value: toStr || "now" },
      { Field: "Generated", Value: new Date().toISOString() },
      { Field: "Generated by", Value: user.name || user.email },
      ...Object.entries(counts).map(([k, v]) => ({ Field: `${k} records`, Value: v })),
    ];
    XLSX.utils.book_append_sheet(
      wb,
      XLSX.utils.json_to_sheet(summary),
      "Summary"
    );
    // Move Summary to the front.
    wb.SheetNames = ["Summary", ...wb.SheetNames.filter((n) => n !== "Summary")];

    const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" }) as Buffer;

    const ctx = await requestContext();
    await logActivity({
      employeeId: user.isEnvAdmin ? null : user.id,
      employeeName: user.name,
      employeeRole: user.role,
      action: `downloaded a database backup (${fromStr || "start"} → ${toStr || "now"})`,
      module: "reports",
      ...ctx,
    });

    const filename = `SOMART-backup_${fromStr || "start"}_to_${toStr || "now"}.xlsx`;
    return new NextResponse(new Uint8Array(buf), {
      status: 200,
      headers: {
        "Content-Type":
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err) {
    console.error("GET /api/backup failed:", err);
    return NextResponse.json({ error: "Backup failed" }, { status: 500 });
  }
}
